Project/comp8347/Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls', namespace='courses')),
    path('', include('blog.urls', namespace='blogs')),
    path('', include('club.urls', namespace='club')),
    path('', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/comp8347/blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),


]

Project/comp8347/club/urls.py
from django.urls import path

from club.views import ClubView, PayView

app_name = 'club'

urlpatterns = [
    path('club/', ClubView.as_view(), name='club_details'),
    path('pay/', PayView.as_view(), name='pay'),
]

Project/comp8347/club/models.py
from django.db import models
from django.contrib.auth.models import User


class Club(models.Model):
    tier = models.CharField(max_length=51)
    price = models.IntegerField(default=35)
    details = models.TextField(blank=True)

    def __str__(self):
        return f"Tier: {self.tier}, pricing: ${self.price}"

    def create_tier(self, name, price, details=""):
        club = Club()
        club.name, club.price, club.details = name, price, details
        Club.objects.create(club)
        print(f"Club objects: {Club.objects.all()}")
    
    def has_tier(self, tier):
            return self.tier == tier

    class Meta:
        ordering = ['price']


class Fx(models.Model):
    fx_name = models.CharField(max_length=25, default="Canadian Dollar")
    fx_sign = models.CharField(max_length=5, default="C$")
    fx_code = models.CharField(max_length=5, default="CAD")

    def __str__(self):
        return f"{self.fx_name}, {self.fx_code}, {self.fx_sign}"

    class Meta:
        ordering = ['fx_name']


class Order(models.Model):
    order_id = models.CharField(max_length=100)
    user_id = models.IntegerField()
    tier = models.CharField(max_length=10)
    amount_cad = models.IntegerField()
    amount_fx = models.DecimalField(max_digits=10, decimal_places=2)
    fx_choice = models.IntegerField()
    order_time = models.DateTimeField()
    card_last_6 = models.IntegerField(max_length=6)
    result = models.BooleanField()

    def __str__(self):
        user = User.objects.get(id=self.user_id)
        return f"{self.order_id}, {user}, {self.tier}, {self.amount_cad}, {self.result}"

# class Membership(models.Model):
#     slug = models.SlugField()
#     membership_type = models.CharField(choices=MEMBERSHIP_CHOICES, default='Free', max_length=30)
#     price = models.IntegerField(default=15)
#     stripe_plan_id = models.CharField(max_length=40)
#
#     def __str__(self):
#         return self.membership_type
#
#
# class UserMembership(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     stripe_customer_id = models.CharField(max_length=40)
#     membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True, blank=True)
#
#     def __str__(self):
#         return self.user.username
#
#
# def post_save_create_user_membership(sender, instance, created, *args, **kwargs):
#     if created:
#         UserMembership.objects.get_or_create(user=instance)
#     user_membership, created = UserMembership.objects.get_or_create(user=instance)
#     if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
#         new_customer_id = stripe.Customer.create(email=instance.email)
#         user_membership.stripe_customer_id = new_customer_id['id']
#         user_membership.save()
#
#
# post_save.connect(post_save_create_user_membership, User)
#

Project/comp8347/club/forms.py
from django import forms
from club.models import Club, Fx


class TierForm(forms.Form):
    tiers = Club.objects.all()
    data = []
    for tier in tiers:
        data.append((tier.id, tier.tier))

    options = forms.ChoiceField(
        choices=data,
        label="Select your tier here",
        widget=forms.Select(attrs={'class': 'form-control'})
    )


class FxForm(forms.Form):
    fxs = Fx.objects.all()
    data = []
    for fx in fxs:
        data.append((fx.id, fx.fx_name))

    fx_choice = forms.ChoiceField(
        choices=data,
        label="Select your Currency here",
        widget=forms.Select(attrs={'class': 'form-control'})
    )


from django import forms

class PaymentForm(forms.Form):
    card_number = forms.CharField(
        max_length=16,
        min_length=16,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    card_expiry_month = forms.IntegerField(
        max_value=12,
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    card_expiry_year = forms.IntegerField(
        max_value=99,
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    card_expiry_cvv = forms.CharField(
        min_length=3,
        max_length=3,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

Project/comp8347/club/views.py
import datetime
import json

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View

from club.FxUtil import compute_fx_amount, SYMBOL_MAP, clear_fx_cache
from club.forms import TierForm, FxForm, PaymentForm
from club.models import Club, Fx, Order
from courses.models import Course
from users.models import Profile, User


def compute_fx_details(price):
    data = {}
    for currency in SYMBOL_MAP.keys():
        data[currency] = compute_fx_amount(currency, price)
    return data


class ClubView(View):

    def get(self, request):
        fx_form = FxForm()
        return render(request, "club/club_details.html", context={'fx_form': fx_form, 'type': 'get'})

    def post(self, request):
        clear_fx_cache()

        fx_choice = Fx.objects.get(id=request.POST['fx_choice'])
        print(fx_choice.fx_code)
        clubs = Club.objects.all()
        # print(f"Club details => {clubs}")
        club_details = {}
        fx_details = {}
        courses = Course.objects.all()
        for club in clubs:
            # print(f"Club data => {club}, club detail => {club.details}")
            tier = club.tier
            details = [course.title.strip() for course in courses.filter(club=club)]
            club_details[tier] = details
            fx_details[club.price] = compute_fx_details(club.price)
        # print(club_details)
        print(fx_details)
        tier_form = TierForm()
        request.session['fx_id'] = fx_choice.id
        request.session['fx_details'] = json.dumps(fx_details)
        print(request.session['fx_details'])
        return render(request, "club/club_details.html", context={'tiers': clubs,
                                                                  'club_details': club_details,
                                                                  'tier_form': tier_form,
                                                                  'fx_details': fx_details,
                                                                  'fx_choice': fx_choice.fx_code,
                                                                  'fx_sign': fx_choice.fx_sign})


def compute_uuid():
    import uuid
    return uuid.uuid4()


def save_order(session_data, card_details, outcome):
    current_dt = datetime.datetime.now()
    fx_amount = session_data['fx_amount']
    fx_choice = session_data['fx_choice']
    amount = session_data['amount']
    order_id = session_data['oid']
    user_id = session_data['uid']
    tier = session_data['tier']
    card_detail = card_details.get('card_number', '0000000000000000')
    order = Order.objects.create(order_id=order_id,
                                 user_id=user_id,
                                 tier=tier,
                                 amount_cad=amount,
                                 amount_fx=fx_amount,
                                 fx_choice=fx_choice,
                                 order_time=current_dt,
                                 card_last_6=card_detail,
                                 result=outcome)
    print(f"Saved order {order}")
    club = Club.objects.filter(tier=tier).first()
    profile = Profile.objects.filter(user=User.objects.get(id=user_id)).first()
    profile.set_club(club)
    profile.save()
    [course.update_student_count() for course in Course.objects.all()]
    print(f"Profile of {profile} updated with club being {profile.club}")
    return order


@method_decorator(login_required, name='post')  # to enforce login is done before accessing the post method
class PayView(View):
    def get(self, request):
        return redirect('club:club_details')

    def post(self, request):
        if "card_number" not in request.POST:
            print(f"Post data => {request.POST}")
            fx = Fx.objects.get(id=request.session['fx_id'])
            fx_details = dict(json.loads(request.session['fx_details']))
            user_id = request.user.id
            order_id = compute_uuid()
            tier = Club.objects.get(id=request.POST['options'])
            amount = fx_details.get(str(tier.price)).get(fx.fx_code)
            pay_form = PaymentForm()

            # request.session.clear()
            request.session['fx_amount'] = amount
            request.session['fx_choice'] = fx.id
            request.session['amount'] = tier.price
            request.session['oid'] = str(order_id)
            request.session['uid'] = user_id
            request.session['tier'] = tier.tier

            if tier.tier == "Free":
                save_order(request.session, request.POST, True)
                return render(request, "club/paymentOk.html")

            return render(request, "club/payment.html", context={
                "tier": tier,
                "fx_sign": fx.fx_sign,
                "amount": amount,
                "pay_form": pay_form
            })
        else:
            # the user has entered some details and here we need to request the external server for payment status
            import requests
            txn = requests.post("http://127.0.0.1:8083/pay", data=dict(request.POST), timeout=5)
            data = json.loads(txn.content)

            if data['result'] == "Ok":
                print("Payment done!")
                save_order(request.session, request.POST, True)
                return render(request, "club/paymentOk.html")
            else:
                print("Payment failed!")
                save_order(request.session, request.POST, False)
                return render(request, "club/paymentFail.html")

Project/comp8347/club/templates/club/club_details.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- Page info -->
<div
  class="page-info-section set-bg"
  id="club_detail"
  data-setbg="{% static 'webuni/img/page-bg/1.jpg' %}"
>
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Club details</span>
    </div>
  </div>
</div>
<!-- Page info end -->
    <div class="container">
        <h1 class="display-5 text-center">Club Tiers</h1>
        {% if type != 'get' %}
            <div class="row">
                <div class="d-flex vh-100 justify-content-center align-items-center">
                    {% for tier in tiers %}
                        <div class="rounded border m-1 p-1">
                            <h3 class="px-1">{{ tier.tier }}</h3>
                            {% for key, value in fx_details.items %}
                                {% if key == tier.price %}
                                    {% for fx, fx_value in value.items %}
                                        {% if fx_choice == fx %}
                                            <h4 class="lead my-1 px-1">Price: {{ fx_sign }}{{ fx_value|floatformat:2 }} per month</h4>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                            <p class="text-small mt-1 px-1">Courses included in this tier:</p>
                            <ul class="list-group">
                                {% for key, detail in club_details.items %}
                                    {% if key == tier.tier %}
                                        {% for data in detail %}
                                            <li class="list-group-item">{{ data }}</li>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                  <div class="d-flex justify-content-center align-items-center py-2">
                    <div class="rounded border p-3">
                      <form method="post" action="{% url 'club:pay' %}">
                        {% csrf_token %}
                        {{ tier_form.as_div }}
                        <input type="submit" class="site-btn btn-dark mt-2" value="Proceed">
                      </form>
                    </div>
                  </div>
                </div>
            </div>
        {% else %}
            <div class="row">
                <div class="col-12">
                  <div class=" d-flex justify-content-center align-items-center py-2 ">
                    <div class="rounded border p-3">
                      <form method="post" action="{% url 'club:club_details' %}">
                        {% csrf_token %}
                        {{ fx_form.as_div }}
                        <input type="submit" class="site-btn btn-dark mt-2" value="Proceed">
                      </form>
                    </div>
                  </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock content %}

Project/comp8347/club/templates/club/payment.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- Page info -->
<div
  class="page-info-section set-bg"
  data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}"
>
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Payment</span>
    </div>
  </div>
</div>

<div class='container'>
    <h1>Payment</h1>
    <div class="row">
        <p>Tier Chosen : {{ tier.tier }}</p>
        <p>Price : {{ fx_sign }} {{ amount|floatformat:2 }} per month</p>
        <div class="col-12">
            <div class="d-flex justify-content-center align-items-center py-2">
                <div class="rounded border p-3">
                    <form action="{% url 'club:pay' %}" method="post">
                        {% csrf_token %}
                        {{ pay_form.as_p }}
                        <input type="submit" class="site-btn btn-dark mt-2" value="Pay">
                    </form>      
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Project/comp8347/club/templates/club/paymentFail.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- Page info -->
<div
  class="page-info-section set-bg"
  data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}"
>
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Payment Failed</span>
    </div>
  </div>
</div>

<div class="d-flex flex-column align-items-center justify-content-center">
  <img src="{% static 'webuni/img/payment/failed.png'%}" alt="failed" />
  <p class="display-4">Payment Failed</p>
</div>

{% comment %} <!DOCTYPE html>
<html>
  <body>
    <h1>Payment failed!!</h1>
  </body>
</html>
{% endcomment %} {% endblock %}

Project/comp8347/club/templates/club/paymentOk.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- Page info -->
<div
  class="page-info-section set-bg"
  data-setbg="{% static 'webuni/img/page-bg/2.jpg' %}"
>
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Payment Successful</span>
    </div>
  </div>
</div>

<div class="d-flex flex-column align-items-center justify-content-center">
  <img src="{% static 'webuni/img/payment/success.png'%}" alt="success" />
  <p class="display-4">Payment Successful</p>
</div>

{% comment %} <!DOCTYPE html>
<html>
  <body>
    <h1>Payment failed!!</h1>
  </body>
</html>
{% endcomment %} {% endblock %}