Project/comp8347/Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls', namespace='courses')),
    path('', include('blog.urls', namespace='blogs')),
    path('', include('club.urls', namespace='club')),
    path('', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/comp8347/blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),


]

Project/comp8347/club/urls.py
from django.urls import path

from club.views import ClubView, PayView

app_name = 'club'

urlpatterns = [
    path('club/', ClubView.as_view(), name='club_details'),
    path('pay/', PayView.as_view(), name='pay'),
]

Project/comp8347/courses/urls.py
from django.urls import path

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView, RequestTeacherView, CourseSearchView

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/<slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', LessonDetailView.as_view(), name='lesson_detail'),
    path('request_teacher/', RequestTeacherView.as_view(), name='request_teacher'),
    path('search/', CourseSearchView.as_view(), name='course_search')
]

Project/comp8347/users/urls.py
from django.urls import path

from users.views import Profile

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),

]

Project/comp8347/templates/about.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Page info -->
<div
  class="page-info-section set-bg"
  id="about-us-info-section"
  data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}"
>
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>About</span>
    </div>
  </div>
</div>
<!-- Page info end -->

<section class="about-us py-5" id="about-us">
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-6">
        <h1 class="primary-text py-5">Welcome to CoursePro!</h1>
        <h2>Know More About Us</h2>
        <hr />
        <p>
          We are passionate about learning and dedicated to providing
          high-quality education to learners of all ages and backgrounds. Our
          mission is to make education accessible and enjoyable for everyone,
          empowering individuals to achieve their full potential.
        </p>
        <p>
          Our vision is to create a global learning ecosystem where knowledge
          knows no boundaries. We aim to foster a love for learning, enabling
          people from all walks of life to enhance their skills, grow their
          careers, and explore new horizons.
        </p>
        <p>
          Our platform is designed to be easy to use and accessible on any
          device. You can learn at your own pace, on your own schedule, and from
          anywhere in the world. We also offer a variety of resources and tools
          to help you succeed, including quizzes, assignments, and discussion
          forums.
        </p>
        <p>
          Join the CoursePro community today and start learning from the best!
        </p>
        <button type="button" class="btn btn-primary-color">
          Let's Know More
        </button>
      </div>
      <div class="col-md-6">
        <img src="{% static 'webuni/img/about.jpg'%}" alt="about" />
      </div>
    </div>
  </div>
</section>
{% endblock %}

Project/comp8347/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>CoursePro - COMP8347</title>
    <meta charset="UTF-8">
    <meta name="description" content="WebUni Education Template">
    <meta name="keywords" content="webuni, education, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicon -->
    <link href="img/favicon.ico" rel="shortcut icon"/>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
    <link rel="stylesheet" href="{% static 'webuni/css/style.css' %}?v={% now 'U' %}"/>

</head>
<body>
<!-- Page Preloder -->
<div id="preloader">
    <div class="dot dot-1"></div>
    <div class="dot dot-2"></div>
    <div class="dot dot-3"></div>
</div>

<!-- Header section -->
<header class="header-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="site-logo">
                    <img src="{% static 'webuni/img/logo.png' %}" alt="">
                </div>
                <div class="nav-switch">
                    <i class="fa fa-bars"></i>
                </div>
            </div>
            <div class="col-lg-9 col-md-9">
                <nav class="main-menu">
                    <ul>
                        <li><a href="{% url 'courses:home' %}">Home</a></li>
                        <li><a href="{% url 'courses:about' %}">About us</a></li>
                        <li><a href="{% url 'courses:course_list' %}">Courses</a></li>
                        <li><a href="{% url 'blogs:post_list' %}">News</a></li>
                        <li><a href="{% url 'courses:contact' %}">Contact</a></li>
                        <li><a href="{% url 'club:club_details' %}">Membership</a></li>
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'users:profile' %}" class="site-btn header-btn">Dashboard : {{ request.user.username }}</a></li>
                            <li><a href="{% url 'account_logout' %}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'account_login' %}" class="site-btn header-btn">Login</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>
<!-- Header section end -->
{% include 'inc/messages.html' %}
{% block content %}

{% endblock content %}


<!-- banner section -->
{% comment %} <section class="banner-section spad">
    <div class="container">
        <div class="section-title mb-0 pb-2">
            <h2>Join Our Community Now!</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus
                finibus.</p>
        </div>
        <div class="text-center pt-5">
            <a href="{% url 'account_signup' %}" class="site-btn">Register Now</a>
        </div>
    </div>
</section> {% endcomment %}
<!-- banner section end -->
<footer class="bg-dark text-light py-4 mt-4">
    <div class="container">
      <div class="d-flex justify-content-center">
        <ul class="list-unstyled footer-menu d-flex flex-wrap">
          <li><a class="text-light" href="{% url 'courses:home' %}">Home</a></li>
          <li><a class="text-light" href="{% url 'courses:about' %}">About us</a></li>
          <li><a class="text-light" href="{% url 'courses:course_list' %}">Courses</a></li>
          <li><a class="text-light" href="{% url 'blogs:post_list' %}">News</a></li>
          <li><a class="text-light" href="{% url 'courses:contact' %}">Contact</a></li>
          <li><a class="text-light" href="{% url 'club:club_details' %}">Membership</a></li>
        </ul>
      </div>
      <hr>
      <div class="row">
        <div class="col-lg-12">
          <p class="text-center">
            &copy; 2023 CoursePro. All Rights Reserved.
          </p>
        </div>
      </div>
    </div>
  </footer>
{% comment %} <div class="footer-bottom">
    <div class="footer-warp">
      <div class="text-center">
        <span>&copy; CoursePro 2023</span>
      </div>
    </div>
</div> {% endcomment %}


<!-- footer section -->
{% comment %} <footer class="footer-section spad pb-0">
    <div class="footer-top">
        <div class="footer-warp">
            <div class="row">
                <div class="widget-item">
                    <h4>Contact Info</h4>
                    <ul class="contact-list">
                        <li>Sunset Ave. <br>Windsor, CA N9B 23A</li>
                        <li>+256 242 1200</li>
                        <li>coursepro@gmail.com</li>
                    </ul>
                </div>
                <div class="widget-item">
                    <h4>Engeneering</h4>
                    <ul>
                        <li><a href="">Applied Studies</a></li>
                        <li><a href="">Computer Engeneering</a></li>
                        <li><a href="">Software Engeneering</a></li>
                        <li><a href="">Informational Engeneering</a></li>
                        <li><a href="">System Engeneering</a></li>
                    </ul>
                </div>
                <div class="widget-item">
                    <h4>Graphic Design</h4>
                    <ul>
                        <li><a href="">Applied Studies</a></li>
                        <li><a href="">Computer Engeneering</a></li>
                        <li><a href="">Software Engeneering</a></li>
                        <li><a href="">Informational Engeneering</a></li>
                        <li><a href="">System Engeneering</a></li>
                    </ul>
                </div>
                <div class="widget-item">
                    <h4>Development</h4>
                    <ul>
                        <li><a href="">Applied Studies</a></li>
                        <li><a href="">Computer Engeneering</a></li>
                        <li><a href="">Software Engeneering</a></li>
                        <li><a href="">Informational Engeneering</a></li>
                        <li><a href="">System Engeneering</a></li>
                    </ul>
                </div>
                <div class="widget-item">
                    <h4>Newsletter</h4>
                    <form class="footer-newslatter">
                        <input type="email" placeholder="E-mail">
                        <button class="site-btn">Subscribe</button>
                        <p>*We don’t spam</p>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="footer-warp">
          <div class="text-center">
            <span>&copy; CoursePro 2023</span>
          </div>
        </div>
    </div>
</footer> {% endcomment %}
<!-- footer section end -->


<!--====== Javascripts & Jquery ======-->
<script async src="https://relayv2-dev.s3.amazonaws.com/analytics/distrobird_widget.js" data-widget-uid="c97e3cb3-9d88-42cc-a467-9288c7075e84"></script>
<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'webuni/js/main.js' %}?v={% now 'U' %}"></script>
</html>

Project/comp8347/templates/contact.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- Page info -->
<div
  class="page-info-section set-bg"
  data-setbg="{% static 'webuni/img/page-bg/5.jpg' %}"
>
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Home</a>
      <span>Contact</span>
    </div>
  </div>
</div>
<!-- Page info end -->

<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Search for Your Course</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form
            method="GET"
            class="course-search-form"
            action="{% url 'courses:course_search' %}"
          >
            <input
              type="text"
              name="q"
              placeholder="Course Title"
              value="{{ request.GET.q }}"
            />
            <input
              type="text"
              name="category"
              placeholder="Category"
              value="{{ request.GET.category }}"
            />
            <button type="submit" class="site-btn btn-dark">
              Search Course
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->

<!-- Page -->
<section class="contact-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="contact-form-warp">
          <div class="section-title text-white text-left">
            <h2>Get in Touch</h2>
            <p>Share Your Thoughts With Us.</p>
          </div>
          {% comment %}
          <form class="contact-form">
            <input type="text" placeholder="Your Name" />
            <input type="email" placeholder="Your E-mail" />
            <input type="text" placeholder="Subject" />
            <textarea placeholder="Message"></textarea>
            <button class="site-btn">Send Message</button>
          </form>
          {% endcomment %} {% if success %}
          <div class="alert alert-success" role="alert">
            Thank you for your message!
          </div>
          {% endif %}
          <form
            class="contact-form"
            method="post"
            action="{% url 'courses:contact' %}"
          >
            {% csrf_token %}
            <div class="form-group">
              <label for="name">Your Name</label>
              <input
                type="text"
                class="form-control"
                id="name"
                name="name"
                placeholder="Your Name"
                required
              />
            </div>
            <div class="form-group">
              <label for="email">Your E-mail</label>
              <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="Your E-mail"
                required
              />
            </div>
            <div class="form-group">
              <label for="subject">Subject</label>
              <input
                type="text"
                class="form-control"
                id="subject"
                name="subject"
                placeholder="Subject"
                required
              />
            </div>
            <div class="form-group">
              <label for="message">Message</label>
              <textarea
                class="form-control"
                id="message"
                name="message"
                placeholder="Message"
                required
              ></textarea>
            </div>
            <button type="submit" class="site-btn">Send Message</button>
          </form>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="contact-info-area">
          <div class="section-title text-left p-0">
            <h2>Contact Info</h2>
            <p>
              We'd love to hear from you! Get in touch with us and we'll get
              back to you as soon as we can.
            </p>
          </div>
          <div class="phone-number">
            <span>Direct Line</span>
            <h2>+2348091356855</h2>
          </div>
          <ul class="contact-list">
            <li>Sunset <br />Windsor, CA N9B 2A8</li>
            <li>+2348091356855</li>
            <li>contact@coursepro.com</li>
          </ul>
          <div class="social-links">
            <a href="#"><i class="fa fa-pinterest"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

Project/comp8347/templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Hero section -->
<!-- Hero section with a background image -->
<section
  class="hero-section set-bg"
  data-setbg="{% static 'webuni/img/bg.png'%}"
>
  <div class="container">
    <!-- Hero text with a title and description -->
    <div class="hero-text text-white">
      <h2>Get The Best Premium Online Courses</h2>
      <p>
        We offer a wide range of courses spanning various subjects, from
        academic topics to professional development and personal growth. Our
        diverse course catalog ensures that learners can find the perfect fit
        for their interests and goals
      </p>
    </div>
    <!-- Search form for courses with input fields for course name and category -->
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <form
          method="GET"
          class="course-search-form"
          action="{% url 'courses:course_search' %}"
        >
          <input
            type="text"
            name="q"
            placeholder="Course Title"
            value="{{ request.GET.q }}"
          />
          <input
            type="text"
            name="category"
            placeholder="Category"
            value="{{ request.GET.category }}"
          />
          <button type="submit" class="site-btn btn-dark">Search Course</button>
        </form>
        {% comment %}
        <form
          method="GET"
          class="course-search-form"
          action="{% url 'courses:course_search' %}"
        >
          <input type="text" placeholder="Enter course name" />
          <input
            type="text"
            class="last-s"
            placeholder="Enter course category"
          />
          <button class="site-btn">Search Courses</button>
        </form>
        {% endcomment %}
      </div>
    </div>
  </div>
</section>
<!-- Hero section end -->

<!-- categories section -->
<section class="categories-section spad">
  <div class="container">
    <!-- Section title with a heading and description -->
    <div class="section-title">
      <h2>Our Course Categories</h2>
      <p>
        Explore the digital universe with our technology courses, covering
        programming, web development, and design.
      </p>
    </div>
    <!-- Course categories displayed as cards -->
    <div class="row">
      {% for category, course_count in categories %}
      <!-- categorie -->
      <div class="col-lg-4 col-md-6 p-2">
        <div class="category-item">
          <img
            class="ci-thumb"
            src="{{ category.image.url }}"
            alt="{{ category.category }}"
          />
          <div class="ci-text">
            <h5 class="h5">{{category.category|capfirst}}</h5>
            <p class="card-text">
              <small class="lead text-center">{{course_count}} Courses</small>
            </p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- categories section end -->

<!-- signup section -->
<section class="signup-section spad">
  <div
    class="signup-bg set-bg"
    data-setbg="{% static 'webuni/img/signup-bg.jpg' %}"
  ></div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6">
        <div class="signup-warp">
          <div class="section-title text-white text-left">
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
              </ul>
            {% endif %}
            <h2>Sign up to become a teacher</h2>
            <p>
              Join our e-learning portal as an instructor and share your
              expertise with a global community of learners. Empower minds and
              inspire growth through teaching with us.
            </p>
          </div>
          <!-- signup form -->
          <form
            class="signup-form"
            method="POST"
            action="{% url 'courses:request_teacher' %}"
          >
            {% csrf_token %}
            <input type="text" placeholder="Your Name" name="name" />
            <input type="text" placeholder="Your E-mail" name="e-mail" />
            <input type="text" placeholder="Your Phone" name="phone" />
            <button class="site-btn">Make Request</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- signup section end -->

{% endblock content %}